[book]
authors = ["blackanger"]
language = "zh"
multilingual = false
src = "src"
title = "RustCodingGuidelines"

[build]
create-missing = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/Rust-Coding-Guidelines/rust-coding-guidelines-zh"

[output.html.fold]
enable = true
level = 0